version: '3.8'

services:
  postgres:
    container_name: postgres-sql
    image: postgres:15
    environment:
      - POSTGRES_DB=zwigato
      - POSTGRES_USER=amit
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5438:5432"
    volumes:
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
      - postgres:/var/lib/postgresql/data
    networks:
      - backend-service
    restart: unless-stopped

  flyway:
    container_name: flyway
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres/zwigato -user=amit -password=admin migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/db/migration
    depends_on:
      - postgres
    networks:
      - backend-service

volumes:
  postgres:
    driver: local
networks:
    backend-service:
        driver: bridge